name: 'AppendToFile Action'
description: 'Appends text to a file (if it is not already there)'
inputs:
  textToSearch:
    description: 'The required text in a file'
    required: true
  textToAdd:
    description: 'The required text to add to a file (if not present)'
    required: true
  insertFileName:
    description: 'Specific to this use-case - add file-name for survey if set to true'
    required: false
  paths:
    description: 'Paths to the changed files'
    required: false
runs:
  using: 'node16'
  main: 'index.js'